import "./globals.css";

// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-inter antialiased leading-relaxed selection:bg-purple selection:text-indigo-200`}
      >
        <div id="__next">{children}</div>
      </body>
    </html>
  );
}
