"use client";

import "./globals.css";
import { AuthProvider } from "@/contexts/auth/AuthContext";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`h-full font-inter antialiased leading-relaxed selection:bg-purple selection:text-indigo-200`}
      >
        <div id="__next">
          <AuthProvider>{children}</AuthProvider>
        </div>
      </body>
    </html>
  );
}
